BEGIN;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'player' CHECK (role IN ('admin', 'dm', 'player')),
    display_name VARCHAR(120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_username_lower ON users ((lower(username)));

CREATE TABLE campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    dm_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_campaigns_dm_id ON campaigns(dm_id);

CREATE TABLE campaign_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL DEFAULT 'player' CHECK (role IN ('dm', 'player')),
    approved BOOLEAN NOT NULL DEFAULT FALSE,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (campaign_id, user_id)
);

CREATE INDEX idx_campaign_memberships_user_id ON campaign_memberships(user_id);

CREATE TABLE character_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(200) NOT NULL,
    is_npc_template BOOLEAN NOT NULL DEFAULT FALSE,
    description TEXT,
    race VARCHAR(80),
    char_class VARCHAR(80),
    background VARCHAR(80),
    alignment VARCHAR(40),
    level INTEGER NOT NULL DEFAULT 1 CHECK (level BETWEEN 1 AND 30),
    strength INTEGER NOT NULL DEFAULT 10 CHECK (strength BETWEEN 1 AND 30),
    dexterity INTEGER NOT NULL DEFAULT 10 CHECK (dexterity BETWEEN 1 AND 30),
    constitution INTEGER NOT NULL DEFAULT 10 CHECK (constitution BETWEEN 1 AND 30),
    intelligence INTEGER NOT NULL DEFAULT 10 CHECK (intelligence BETWEEN 1 AND 30),
    wisdom INTEGER NOT NULL DEFAULT 10 CHECK (wisdom BETWEEN 1 AND 30),
    charisma INTEGER NOT NULL DEFAULT 10 CHECK (charisma BETWEEN 1 AND 30),
    traits JSONB NOT NULL DEFAULT '{}'::jsonb,
    notes TEXT,
    times_used INTEGER NOT NULL DEFAULT 0 CHECK (times_used >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_character_templates_owner_id ON character_templates(owner_id);

CREATE TABLE characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    campaign_id BIGINT REFERENCES campaigns(id) ON DELETE CASCADE,
    is_npc BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(200) NOT NULL DEFAULT '(unnamed)',
    level INTEGER NOT NULL DEFAULT 1 CHECK (level BETWEEN 1 AND 30),
    char_class VARCHAR(80),
    subclass VARCHAR(80),
    race VARCHAR(80),
    background VARCHAR(80),
    alignment VARCHAR(40),
    experience_points INTEGER NOT NULL DEFAULT 0 CHECK (experience_points >= 0),
    strength INTEGER NOT NULL DEFAULT 10 CHECK (strength BETWEEN 1 AND 30),
    dexterity INTEGER NOT NULL DEFAULT 10 CHECK (dexterity BETWEEN 1 AND 30),
    constitution INTEGER NOT NULL DEFAULT 10 CHECK (constitution BETWEEN 1 AND 30),
    intelligence INTEGER NOT NULL DEFAULT 10 CHECK (intelligence BETWEEN 1 AND 30),
    wisdom INTEGER NOT NULL DEFAULT 10 CHECK (wisdom BETWEEN 1 AND 30),
    charisma INTEGER NOT NULL DEFAULT 10 CHECK (charisma BETWEEN 1 AND 30),
    max_hp INTEGER NOT NULL DEFAULT 0 CHECK (max_hp >= 0),
    current_hp INTEGER NOT NULL DEFAULT 0 CHECK (current_hp >= 0),
    temp_hp INTEGER NOT NULL DEFAULT 0 CHECK (temp_hp >= 0),
    armor_class INTEGER NOT NULL DEFAULT 10 CHECK (armor_class >= 0),
    initiative INTEGER NOT NULL DEFAULT 0,
    speed INTEGER NOT NULL DEFAULT 30 CHECK (speed >= 0),
    proficiency_bonus INTEGER NOT NULL DEFAULT 2,
    hit_dice VARCHAR(20),
    skills JSONB NOT NULL DEFAULT '{}'::jsonb,
    saving_throws JSONB NOT NULL DEFAULT '{}'::jsonb,
    equipment JSONB NOT NULL DEFAULT '[]'::jsonb,
    spells JSONB NOT NULL DEFAULT '{}'::jsonb,
    features JSONB NOT NULL DEFAULT '[]'::jsonb,
    traits JSONB NOT NULL DEFAULT '{}'::jsonb,
    attacks JSONB NOT NULL DEFAULT '[]'::jsonb,
    notes TEXT,
    build_step INTEGER NOT NULL DEFAULT 0 CHECK (build_step >= 0),
    build_complete BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_characters_owner_id ON characters(owner_id);
CREATE INDEX idx_characters_campaign_id ON characters(campaign_id);
CREATE INDEX idx_characters_campaign_npc ON characters(campaign_id, is_npc);

COMMIT;
