BEGIN;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'player' CHECK (role IN ('admin', 'dm', 'player')),
    display_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (length(btrim(username)) BETWEEN 1 AND 80),
    CHECK (display_name IS NULL OR length(display_name) <= 120)
);

CREATE UNIQUE INDEX users_username_ci_unique ON users (lower(username));

CREATE TABLE campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    dm_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (length(btrim(name)) BETWEEN 1 AND 200)
);
CREATE INDEX campaigns_dm_id_idx ON campaigns(dm_id);

CREATE TABLE campaign_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role TEXT NOT NULL DEFAULT 'player' CHECK (role IN ('dm', 'player')),
    approved BOOLEAN NOT NULL DEFAULT FALSE,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (campaign_id, user_id)
);
CREATE INDEX campaign_memberships_user_id_idx ON campaign_memberships(user_id);

CREATE TABLE character_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    is_npc_template BOOLEAN NOT NULL DEFAULT FALSE,
    description TEXT,
    race TEXT,
    char_class TEXT,
    background TEXT,
    alignment TEXT,
    level INTEGER NOT NULL DEFAULT 1 CHECK (level BETWEEN 1 AND 30),
    strength INTEGER NOT NULL DEFAULT 10 CHECK (strength BETWEEN 1 AND 30),
    dexterity INTEGER NOT NULL DEFAULT 10 CHECK (dexterity BETWEEN 1 AND 30),
    constitution INTEGER NOT NULL DEFAULT 10 CHECK (constitution BETWEEN 1 AND 30),
    intelligence INTEGER NOT NULL DEFAULT 10 CHECK (intelligence BETWEEN 1 AND 30),
    wisdom INTEGER NOT NULL DEFAULT 10 CHECK (wisdom BETWEEN 1 AND 30),
    charisma INTEGER NOT NULL DEFAULT 10 CHECK (charisma BETWEEN 1 AND 30),
    traits JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(traits) = 'object'),
    notes TEXT,
    times_used INTEGER NOT NULL DEFAULT 0 CHECK (times_used >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (length(btrim(name)) BETWEEN 1 AND 200)
);
CREATE INDEX character_templates_owner_id_idx ON character_templates(owner_id);

CREATE TABLE characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    campaign_id BIGINT REFERENCES campaigns(id) ON DELETE CASCADE,
    is_npc BOOLEAN NOT NULL DEFAULT FALSE,
    name TEXT NOT NULL DEFAULT '(unnamed)',
    level INTEGER NOT NULL DEFAULT 1 CHECK (level BETWEEN 1 AND 30),
    char_class TEXT,
    subclass TEXT,
    race TEXT,
    background TEXT,
    alignment TEXT,
    experience_points INTEGER NOT NULL DEFAULT 0 CHECK (experience_points >= 0),
    strength INTEGER NOT NULL DEFAULT 10 CHECK (strength BETWEEN 1 AND 30),
    dexterity INTEGER NOT NULL DEFAULT 10 CHECK (dexterity BETWEEN 1 AND 30),
    constitution INTEGER NOT NULL DEFAULT 10 CHECK (constitution BETWEEN 1 AND 30),
    intelligence INTEGER NOT NULL DEFAULT 10 CHECK (intelligence BETWEEN 1 AND 30),
    wisdom INTEGER NOT NULL DEFAULT 10 CHECK (wisdom BETWEEN 1 AND 30),
    charisma INTEGER NOT NULL DEFAULT 10 CHECK (charisma BETWEEN 1 AND 30),
    max_hp INTEGER NOT NULL DEFAULT 0 CHECK (max_hp >= 0),
    current_hp INTEGER NOT NULL DEFAULT 0 CHECK (current_hp >= 0),
    temp_hp INTEGER NOT NULL DEFAULT 0 CHECK (temp_hp >= 0),
    armor_class INTEGER NOT NULL DEFAULT 10 CHECK (armor_class >= 0),
    initiative INTEGER NOT NULL DEFAULT 0,
    speed INTEGER NOT NULL DEFAULT 30 CHECK (speed >= 0),
    proficiency_bonus INTEGER NOT NULL DEFAULT 2,
    hit_dice TEXT,
    skills JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(skills) = 'object'),
    saving_throws JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(saving_throws) = 'object'),
    equipment JSONB NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(equipment) = 'array'),
    spells JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(spells) = 'object'),
    features JSONB NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(features) = 'array'),
    traits JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(traits) = 'object'),
    attacks JSONB NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(attacks) = 'array'),
    notes TEXT,
    build_step INTEGER NOT NULL DEFAULT 0 CHECK (build_step >= 0),
    build_complete BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (length(btrim(name)) BETWEEN 1 AND 200)
);
CREATE INDEX characters_owner_id_idx ON characters(owner_id);
CREATE INDEX characters_campaign_id_idx ON characters(campaign_id);

CREATE FUNCTION characterforge_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER characters_set_updated_at
BEFORE UPDATE ON characters
FOR EACH ROW
EXECUTE FUNCTION characterforge_set_updated_at();

COMMIT;
